- name: Check for completions tap
  command: brew tap
  register: btap
  changed_when: False

- name: Add completions tap
  command: brew tap homebrew/completions
  when: btap.stdout.find('completions') == -1

- name: "Install brew packages"
  homebrew: name={{ item }} update_homebrew=yes
  when: ansible_system == "Darwin"
  with_items: brew_packages
