- name: Set go url (Darwin)
  set_fact: go_tar="go{{ go_version }}.{{ go_os }}-{{ go_arch_map[ansible_machine] }}-osx10.8.tar.gz"
  when: ansible_os_family == "Darwin"
  tags:
    - go

- name: Set go url (Linux)
  set_fact: go_tar="go{{ go_version }}.{{ go_os }}-{{ go_arch_map[ansible_machine] }}.tar.gz"
  when: ansible_system == "Linux"
  tags:
    - go

- name: Check for Go installation
  stat: path="{{ binaries }}/go"
  register: gobin
  tags:
    - go

- name: Create GOPATH
  file: path="{{ home }}/Go" state=directory
  tags:
    - go

- name: Download Go
  get_url: url="https://storage.googleapis.com/golang/{{ go_tar }}" dest=.
  when: gobin.stat.exists == False
  notify:
    - Unpack Go tarball
    - Remove Go tarball
  tags:
    - go

