- name: Set go url (Darwin)
  set_fact: go_tar="go{{ go_version }}.{{ go_os }}-{{ go_arch_map[ansible_machine] }}-osx10.8.tar.gz"
  when: ansible_os_family == "Darwin"

- name: Set go url (Linux)
  set_fact: go_tar="go{{ go_version }}.{{ go_os }}-{{ go_arch_map[ansible_machine] }}.tar.gz"
  when: ansible_os_family == "Linux"

- name: Check for Go installation
  stat: path="{{ home }}/Binaries/go"
  register: gobin

- name: Create Go binaries dir
  file: path="{{ home }}/Binaries" state=directory

- name: Create GOPATH
  file: path="{{ home }}/Go" state=directory

- name: Download Go
  get_url: url="https://storage.googleapis.com/golang/{{ go_tar }}" dest=.
  when: gobin.stat.exists == False
  notify:
    - Unpack Go tarball
    - Remove Go tarball

