- name: Check for existing files
  stat: path="{{ home }}/{{ item }}"
  register: dotstats
  with_items:
    - "{{ dotfiles }}"
  tags:
    - dotfiles

- name: Backup existing non-links
  command: mv "{{ home }}/{{ item.item }}" "{{ home }}/{{ item.item }}.orig"
  with_items:
    "{{ dotstats['results'] }}"
  when: item.stat.exists and item.stat.islink is not defined

- name: Create symlinks
  file:
    src="{{ project }}/dotfiles/{{ item }}"
    dest="{{ home }}/{{ item }}"
    state=link
  with_items:
    - "{{ dotfiles }}"
  tags:
    - dotfiles

- name: Ensure virtualenv dir is created
  file: path={{ virtualenv_dir }} state=directory
  tags:
    - dotfiles

- name: Create ~/.localrc
  template: src=.localrc.j2 dest="{{ home }}/.localrc"
  tags:
    - dotfiles
