- name: Create symlinks
  file:
    src="{{ project }}/dotfiles/{{ item }}"
    dest="{{ home }}/{{ item }}"
    state=link
  with_items: dotfiles
  tags:
    - dotfiles

- name: Ensure virtualenv dir is created
  file: path={{ virtualenv_dir }} state=directory
  tags:
    - dotfiles

- name: Create ~/.localrc
  template: src=.localrc.j2 dest="{{ home }}/.localrc"
  tags:
    - dotfiles
