- name: Check for tmux
  command: which tmux 
  register: tmux_bin
  ignore_errors: yes
  tags:
    - tmux

- name: Get the current tmux version
  command: '{{ tmux_bin.stdout.strip() }} -V'
  register: tmuxv
  when: tmux_bin.rc == 0
  tags:
    - tmux

- name: Set the tmuxv if the binary didn't exist
  set_fact:
    tmuxv: "0.0"
  when: tmux_bin.rc != 0

- name: Install tmux
  include: install_tmux.yml
  when: tmuxv.stdout.strip() != "tmux {{ tmux_version }}"
  tags:
    - tmux

- name: Create the .tmux symlink
  file:
    src="{{ project }}/tmux"
    dest="{{ home }}/.tmux"
    state=link
  tags:
    - tmux

- name: Clone tmux plugins
  git: repo={{ item.value }}
       dest={{ project }}/tmux/plugins/{{ item.key }}
       recursive=yes
  with_dict: "{{ tmux_install.plugins }}"
  tags:
    - tmux
