- name: Create the .tmux symlink
  file:
    src="{{ project }}/tmux"
    dest="{{ home }}/.tmux"
    state=link
  tags:
    - tmux

- name: Clone tmux plugins
  git: repo={{ item.value }}
       dest={{ project }}/tmux/plugins/{{ item.key }}
       recursive=yes
  with_dict: "{{ tmux_plugins }}"
  tags:
    - tmux
